services:
  app: 
    image: phonebook-frontend-development
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
     - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL: http://localhost:5001
    container_name: phonebook-frontend-development
  backend:
    image: phonebook-backend-development
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/app
    ports:
     - 5001:5001
    container_name: phonebook_backend-development